from django.contrib import admin
from django.urls import path
from .views import *


from . import views

urlpatterns = [
    path("",views.index,name='index'),
    path("homepage/",views.homepage,name='homepage'),
    path("crime_in_india/",views.homepage,name='homepage'),
    path("data_and_visualisation/",views.data_and_visualisation,name='data_and_visualisation'),
    path("crime_Hotspots/",views.crime_hotspots,name='crime_hotspots'),
    path('logout/', custom_logout, name='logout'),
    path("know_your_state/",views.know_your_state,name='know_your_state/ut'),
    path("know_your_state/andhra_pradesh/",andhra_pradesh.as_view(),name='andhra_pradesh'),
    path("about/",views.about,name='about'),
    path("register/",views.register,name='register'),
    path('login/', custom_login, name='login'),
    path('userhome/',views.userhome,name='userhome'),
    path('view/',views.view,name='view'),
    path('moduless/',views.moduless,name='moduless'),
    path('prediction/',views.prediction,name='prediction'),
    path("know_your_state/arunachal_pradesh/", arunachal_pradesh.as_view(), name='arunachal_pradesh'),
    path("know_your_state/assam/", assam.as_view(), name='assam'),
    path('know_your_state/bihar/', bihar.as_view(), name='bihar'),
    path('know_your_state/chhattisgarh/', chhattisgarh.as_view(), name='chhattisgarh'),
    path('know_your_state/goa/', goa.as_view(), name='goa'),
    path('know_your_state/gujarat/', gujarat.as_view(), name='gujarat'),
    path('know_your_state/haryana/', haryana.as_view(), name='haryana'),
    path('know_your_state/himachal_pradesh/', himachal_pradesh.as_view(), name='himachal_pradesh'),
    path('know_your_state/jharkhand/', jharkhand.as_view(), name='jharkhand'),
    path('know_your_state/karnataka/', karnataka.as_view(), name='karnataka'),
    path('know_your_state/kerala/', kerala.as_view(), name='kerala'),
    path('know_your_state/madhya_pradesh/', madhya_pradesh.as_view(), name='madhya_pradesh'),
    path('know_your_state/maharashtra/', maharashtra.as_view(), name='maharashtra'),
    path('know_your_state/manipur/', manipur.as_view(), name='manipur'),
    path('know_your_state/meghalaya/', meghalaya.as_view(), name='meghalaya'),
    path('know_your_state/mizoram/', mizoram.as_view(), name='mizoram'),
    path('know_your_state/nagaland/', nagaland.as_view(), name='nagaland'),
    path('know_your_state/odisha/', odisha.as_view(), name='odisha'),
    path('know_your_state/punjab/', punjab.as_view(), name='punjab'),
    path('know_your_state/rajasthan/', rajasthan.as_view(), name='rajasthan'),
    path('know_your_state/sikkim/', sikkim.as_view(), name='sikkim'),
    path('know_your_state/tamil_nadu/', tamil_nadu.as_view(), name='tamil_nadu'),
    path('know_your_state/telangana/', telangana.as_view(), name='telangana'),
    path('know_your_state/tripura/', tripura.as_view(), name='tripura'),
    path('know_your_state/uttar_pradesh/', uttar_pradesh.as_view(), name='uttar_pradesh'),
    path('know_your_state/uttarakhand/', uttarakhand.as_view(), name='uttarakhand'),
    path('know_your_state/west_bengal/', west_bengal.as_view(), name='west_bengal'),
    path('know_your_state/a&n_islands/', an_islands.as_view(), name='a_and_n_islands'),
    path('know_your_state/chandigarh/', chandigarh.as_view(), name='chandigarh'),
    path('know_your_state/d&n_haveli_and_daman_&_diu/', dadra_and_nagar_haveli_and_daman_and_diu.as_view(), name='dn_haveli_and_daman_and_diu'),
    path('know_your_state/delhi/', delhi.as_view(), name='delhi'),
    path('know_your_state/lakshadweep/', lakshadweep.as_view(), name='lakshadweep'),
    path('know_your_state/puducherry/', puducherry.as_view(), name='puducherry'),
    path('report-crime/', report_crime, name='report_crime'),
    path('save-crime-report/', save_crime_report, name='save_crime_report'),
    path('download-daily-report/', download_report_pdf, name='download_daily_report'),  # Define URL pattern for downloading daily report
    path('admin_dashboard/', admin_dashboard, name='admin_dashboard'),
    #path('status_updated/', views.status_updated, name='status_updated'),
    # path('result',views.result,name='result'),
]